version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: coditor-db
        profiles: ["local"]  #rds사용예정이었으나 시간 부족으로 aiven 그대로 사용
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: Asia/Seoul
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./infra/data/mysql:/var/lib/mysql
        restart: always

    redis:
        image: redis:alpine
        container_name: coditor-redis
        profiles: ["aws", "local"]
        ports:
            - "6379:6379"
        volumes:
            - ./infra/data/redis:/data
        restart: always

    rabbitmq:
        image: rabbitmq:3-management
        container_name: coditor-mq
        profiles: ["aws", "local"]
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - ./infra/data/rabbitmq:/var/lib/rabbitmq
        restart: always

    coditor-api:
        image: ${DOCKER_USERNAME}/coditor-api:latest
        container_name: coditor-api
        profiles: ["aws", "local"]
        ports:
            - "8080:8080"
        env_file:
            - .env
        environment:
            SPRING_PROFILES_ACTIVE: prod
            REDIS_HOST: redis
            RABBITMQ_HOST: rabbitmq
        depends_on:
            - redis
            - rabbitmq
        restart: always

    # 채점 서버
    coditor-worker:
        image: ${DOCKER_USERNAME}/coditor-worker:latest
        container_name: coditor-worker
        profiles: ["worker"]
        env_file:
            - .env
        environment:
            SPRING_PROFILES_ACTIVE: worker
            # 로컬 채점서버는 EC2로 접근
            REDIS_HOST: ${AWS_EC2_HOST}
            RABBITMQ_HOST: ${AWS_EC2_HOST}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./temp_submissions:/app/temp_submissions
        restart: always
